#!/bin/bash

 if [[ $(xrandr -q | grep 'DP-3 connected') ]]; then
   xrandr --output DP-2 --primary --mode 3440x1440 --rate 144 --rotate normal --output DP-3 --mode 2560x2880 --rotate normal --right-of DP-2
fi

pgrep -x sxhkd > /dev/null || sxhkd &

#Bars
bspc monitor eDP-1 -d 1 2 3 4 5 6


bspc config border_width         0
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a ranger state=floating
bspc rule -a state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

bspc rule -a runelite state=floating follow=on

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color2"
 
#This line fixes the 144hz floating windows
bspc config pointer_motion_interval 7ms
#New addition: this controls the pointer control key
bspc config pointer_modifier mod1

wal -R
$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/autostart.sh

